version: '3.6'

services:

  django:
    build: ./app/
    environment:
      # - SECRET_KEY=
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_URL=
    volumes:
      - .:/app/p8_pure_beurre
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    command: bash -c "python3 manage.py migrate && gunicorn --bind=0.0.0.0:8000 app.wsgi:application"
    restart: on-failure
    networks:
      - nginx_network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    restart: on-failure
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: